name: Trigger Integration Tests

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  trigger-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Determine correct SHA
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "COMMIT_SHA=${{ github.event.pull_request.head.sha }}" >> $GITHUB_ENV
          else
            echo "COMMIT_SHA=${{ github.sha }}" >> $GITHUB_ENV
          fi

      - name: Trigger test framework if token is set
        run: |
          if [ -z "${{ secrets.TEST_FRAMEWORK_TOKEN }}" ]; then
            echo "INFO: TEST_FRAMEWORK_TOKEN is not set."
            echo "Skipping test trigger."
          else
            echo "Triggering test framework..."
            curl -X POST https://api.github.com/repos/EmirTutar/ECAL_Test_Framework/dispatches \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Authorization: token ${{ secrets.TEST_FRAMEWORK_TOKEN }}" \
              -d '{
                "event_type": "run-tests",
                "client_payload": {
                  "sha": "'"${{ env.COMMIT_SHA }}"'",
                  "repo": "'"${{ github.repository }}"'",
                  "run_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                }
              }'
          fi

      - name: Test reports and logs
        run: |
          if [ -z "${{ secrets.TEST_FRAMEWORK_TOKEN }}" ]; then
            echo "INFO: TEST_FRAMEWORK_TOKEN is not set."
            echo "Skipping test trigger."
          else
            echo "ECAL-Testsframework has been triggered."
            echo ""
            echo "View status and logs:"
            echo "https://github.com/EmirTutar/ECAL_Test_Framework/actions"
            echo ""
            echo "Test report (available after completion):"
            echo "https://emirtutar.github.io/ECAL_Test_Framework/"
          fi